;; This file is generated automatically. Don't change this file !!
(defvar ac-emoji--data
  '(    (:key ":smile:" :codepoint "\x1f604" :description "smiling face with open mouth and smiling eyes")
    (:key ":smiley:" :codepoint "\x1f603" :description "smiling face with open mouth")
    (:key ":grinning:" :codepoint "\x1f600" :description "grinning face")
    (:key ":blush:" :codepoint "\x1f60a" :description "smiling face with smiling eyes")
    (:key ":relaxed:" :codepoint "\x263a" :description "white smiling face")
    (:key ":wink:" :codepoint "\x1f609" :description "winking face")
    (:key ":heart_eyes:" :codepoint "\x1f60d" :description "smiling face with heart-shaped eyes")
    (:key ":kissing_heart:" :codepoint "\x1f618" :description "face throwing a kiss")
    (:key ":kissing_closed_eyes:" :codepoint "\x1f61a" :description "kissing face with closed eyes")
    (:key ":kissing:" :codepoint "\x1f617" :description "kissing face")
    (:key ":kissing_smiling_eyes:" :codepoint "\x1f619" :description "kissing face with smiling eyes")
    (:key ":stuck_out_tongue_winking_eye:" :codepoint "\x1f61c" :description "face with stuck-out tongue and winking eye")
    (:key ":stuck_out_tongue_closed_eyes:" :codepoint "\x1f61d" :description "face with stuck-out tongue and tightly-closed eyes")
    (:key ":stuck_out_tongue:" :codepoint "\x1f61b" :description "face with stuck-out tongue")
    (:key ":flushed:" :codepoint "\x1f633" :description "flushed face")
    (:key ":grin:" :codepoint "\x1f601" :description "grinning face with smiling eyes")
    (:key ":pensive:" :codepoint "\x1f614" :description "pensive face")
    (:key ":relieved:" :codepoint "\x1f60c" :description "relieved face")
    (:key ":unamused:" :codepoint "\x1f612" :description "unamused face")
    (:key ":disappointed:" :codepoint "\x1f61e" :description "disappointed face")
    (:key ":persevere:" :codepoint "\x1f623" :description "persevering face")
    (:key ":cry:" :codepoint "\x1f622" :description "crying face")
    (:key ":joy:" :codepoint "\x1f602" :description "face with tears of joy")
    (:key ":sob:" :codepoint "\x1f62d" :description "loudly crying face")
    (:key ":sleepy:" :codepoint "\x1f62a" :description "sleepy face")
    (:key ":disappointed_relieved:" :codepoint "\x1f625" :description "disappointed but relieved face")
    (:key ":cold_sweat:" :codepoint "\x1f630" :description "face with open mouth and cold sweat")
    (:key ":sweat_smile:" :codepoint "\x1f605" :description "smiling face with open mouth and cold sweat")
    (:key ":sweat:" :codepoint "\x1f613" :description "face with cold sweat")
    (:key ":weary:" :codepoint "\x1f629" :description "weary face")
    (:key ":tired_face:" :codepoint "\x1f62b" :description "tired face")
    (:key ":fearful:" :codepoint "\x1f628" :description "fearful face")
    (:key ":scream:" :codepoint "\x1f631" :description "face screaming in fear")
    (:key ":angry:" :codepoint "\x1f620" :description "angry face")
    (:key ":rage:" :codepoint "\x1f621" :description "pouting face")
    (:key ":triumph:" :codepoint "\x1f624" :description "face with look of triumph")
    (:key ":confounded:" :codepoint "\x1f616" :description "confounded face")
    (:key ":laughing:" :codepoint "\x1f606" :description "smiling face with open mouth and tightly-closed eyes")
    (:key ":yum:" :codepoint "\x1f60b" :description "face savouring delicious food")
    (:key ":mask:" :codepoint "\x1f637" :description "face with medical mask")
    (:key ":sunglasses:" :codepoint "\x1f60e" :description "smiling face with sunglasses")
    (:key ":sleeping:" :codepoint "\x1f634" :description "sleeping face")
    (:key ":dizzy_face:" :codepoint "\x1f635" :description "dizzy face")
    (:key ":astonished:" :codepoint "\x1f632" :description "astonished face")
    (:key ":worried:" :codepoint "\x1f61f" :description "worried face")
    (:key ":frowning:" :codepoint "\x1f626" :description "frowning face with open mouth")
    (:key ":anguished:" :codepoint "\x1f627" :description "anguished face")
    (:key ":smiling_imp:" :codepoint "\x1f608" :description "smiling face with horns")
    (:key ":imp:" :codepoint "\x1f47f" :description "imp")
    (:key ":open_mouth:" :codepoint "\x1f62e" :description "face with open mouth")
    (:key ":grimacing:" :codepoint "\x1f62c" :description "grimacing face")
    (:key ":neutral_face:" :codepoint "\x1f610" :description "neutral face")
    (:key ":confused:" :codepoint "\x1f615" :description "confused face")
    (:key ":hushed:" :codepoint "\x1f62f" :description "hushed face")
    (:key ":no_mouth:" :codepoint "\x1f636" :description "face without mouth")
    (:key ":innocent:" :codepoint "\x1f607" :description "smiling face with halo")
    (:key ":smirk:" :codepoint "\x1f60f" :description "smirking face")
    (:key ":expressionless:" :codepoint "\x1f611" :description "expressionless face")
    (:key ":man_with_gua_pi_mao:" :codepoint "\x1f472" :description "man with gua pi mao")
    (:key ":man_with_turban:" :codepoint "\x1f473" :description "man with turban")
    (:key ":cop:" :codepoint "\x1f46e" :description "police officer")
    (:key ":construction_worker:" :codepoint "\x1f477" :description "construction worker")
    (:key ":guardsman:" :codepoint "\x1f482" :description "guardsman")
    (:key ":baby:" :codepoint "\x1f476" :description "baby")
    (:key ":boy:" :codepoint "\x1f466" :description "boy")
    (:key ":girl:" :codepoint "\x1f467" :description "girl")
    (:key ":man:" :codepoint "\x1f468" :description "man")
    (:key ":woman:" :codepoint "\x1f469" :description "woman")
    (:key ":older_man:" :codepoint "\x1f474" :description "older man")
    (:key ":older_woman:" :codepoint "\x1f475" :description "older woman")
    (:key ":person_with_blond_hair:" :codepoint "\x1f471" :description "person with blond hair")
    (:key ":angel:" :codepoint "\x1f47c" :description "baby angel")
    (:key ":princess:" :codepoint "\x1f478" :description "princess")
    (:key ":smiley_cat:" :codepoint "\x1f63a" :description "smiling cat face with open mouth")
    (:key ":smile_cat:" :codepoint "\x1f638" :description "grinning cat face with smiling eyes")
    (:key ":heart_eyes_cat:" :codepoint "\x1f63b" :description "smiling cat face with heart-shaped eyes")
    (:key ":kissing_cat:" :codepoint "\x1f63d" :description "kissing cat face with closed eyes")
    (:key ":smirk_cat:" :codepoint "\x1f63c" :description "cat face with wry smile")
    (:key ":scream_cat:" :codepoint "\x1f640" :description "weary cat face")
    (:key ":crying_cat_face:" :codepoint "\x1f63f" :description "crying cat face")
    (:key ":joy_cat:" :codepoint "\x1f639" :description "cat face with tears of joy")
    (:key ":pouting_cat:" :codepoint "\x1f63e" :description "pouting cat face")
    (:key ":japanese_ogre:" :codepoint "\x1f479" :description "japanese ogre")
    (:key ":japanese_goblin:" :codepoint "\x1f47a" :description "japanese goblin")
    (:key ":see_no_evil:" :codepoint "\x1f648" :description "see-no-evil monkey")
    (:key ":hear_no_evil:" :codepoint "\x1f649" :description "hear-no-evil monkey")
    (:key ":speak_no_evil:" :codepoint "\x1f64a" :description "speak-no-evil monkey")
    (:key ":skull:" :codepoint "\x1f480" :description "skull")
    (:key ":alien:" :codepoint "\x1f47d" :description "extraterrestrial alien")
    (:key ":hankey:" :codepoint "\x1f4a9" :description "pile of poo")
    (:key ":fire:" :codepoint "\x1f525" :description "fire")
    (:key ":sparkles:" :codepoint "\x2728" :description "sparkles")
    (:key ":star2:" :codepoint "\x1f31f" :description "glowing star")
    (:key ":dizzy:" :codepoint "\x1f4ab" :description "dizzy symbol")
    (:key ":boom:" :codepoint "\x1f4a5" :description "collision symbol")
    (:key ":anger:" :codepoint "\x1f4a2" :description "anger symbol")
    (:key ":sweat_drops:" :codepoint "\x1f4a6" :description "splashing sweat symbol")
    (:key ":droplet:" :codepoint "\x1f4a7" :description "droplet")
    (:key ":zzz:" :codepoint "\x1f4a4" :description "sleeping symbol")
    (:key ":dash:" :codepoint "\x1f4a8" :description "dash symbol")
    (:key ":ear:" :codepoint "\x1f442" :description "ear")
    (:key ":eyes:" :codepoint "\x1f440" :description "eyes")
    (:key ":nose:" :codepoint "\x1f443" :description "nose")
    (:key ":tongue:" :codepoint "\x1f445" :description "tongue")
    (:key ":lips:" :codepoint "\x1f444" :description "mouth")
    (:key ":+1:" :codepoint "\x1f44d" :description "thumbs up sign")
    (:key ":-1:" :codepoint "\x1f44e" :description "thumbs down sign")
    (:key ":ok_hand:" :codepoint "\x1f44c" :description "ok hand sign")
    (:key ":facepunch:" :codepoint "\x1f44a" :description "fisted hand sign")
    (:key ":fist:" :codepoint "\x270a" :description "raised fist")
    (:key ":v:" :codepoint "\x270c" :description "victory hand")
    (:key ":wave:" :codepoint "\x1f44b" :description "waving hand sign")
    (:key ":hand:" :codepoint "\x270b" :description "raised hand")
    (:key ":open_hands:" :codepoint "\x1f450" :description "open hands sign")
    (:key ":point_up_2:" :codepoint "\x1f446" :description "white up pointing backhand index")
    (:key ":point_down:" :codepoint "\x1f447" :description "white down pointing backhand index")
    (:key ":point_right:" :codepoint "\x1f449" :description "white right pointing backhand index")
    (:key ":point_left:" :codepoint "\x1f448" :description "white left pointing backhand index")
    (:key ":raised_hands:" :codepoint "\x1f64c" :description "person raising both hands in celebration")
    (:key ":pray:" :codepoint "\x1f64f" :description "person with folded hands")
    (:key ":point_up:" :codepoint "\x261d" :description "white up pointing index")
    (:key ":clap:" :codepoint "\x1f44f" :description "clapping hands sign")
    (:key ":muscle:" :codepoint "\x1f4aa" :description "flexed biceps")
    (:key ":walking:" :codepoint "\x1f6b6" :description "pedestrian")
    (:key ":runner:" :codepoint "\x1f3c3" :description "runner")
    (:key ":dancer:" :codepoint "\x1f483" :description "dancer")
    (:key ":couple:" :codepoint "\x1f46b" :description "man and woman holding hands")
    (:key ":family:" :codepoint "\x1f46a" :description "family")
    (:key ":two_men_holding_hands:" :codepoint "\x1f46c" :description "two men holding hands")
    (:key ":two_women_holding_hands:" :codepoint "\x1f46d" :description "two women holding hands")
    (:key ":couplekiss:" :codepoint "\x1f48f" :description "kiss")
    (:key ":couple_with_heart:" :codepoint "\x1f491" :description "couple with heart")
    (:key ":dancers:" :codepoint "\x1f46f" :description "woman with bunny ears")
    (:key ":ok_woman:" :codepoint "\x1f646" :description "face with ok gesture")
    (:key ":no_good:" :codepoint "\x1f645" :description "face with no good gesture")
    (:key ":information_desk_person:" :codepoint "\x1f481" :description "information desk person")
    (:key ":raising_hand:" :codepoint "\x1f64b" :description "happy person raising one hand")
    (:key ":massage:" :codepoint "\x1f486" :description "face massage")
    (:key ":haircut:" :codepoint "\x1f487" :description "haircut")
    (:key ":nail_care:" :codepoint "\x1f485" :description "nail polish")
    (:key ":bride_with_veil:" :codepoint "\x1f470" :description "bride with veil")
    (:key ":person_with_pouting_face:" :codepoint "\x1f64e" :description "person with pouting face")
    (:key ":person_frowning:" :codepoint "\x1f64d" :description "person frowning")
    (:key ":bow:" :codepoint "\x1f647" :description "person bowing deeply")
    (:key ":tophat:" :codepoint "\x1f3a9" :description "top hat")
    (:key ":crown:" :codepoint "\x1f451" :description "crown")
    (:key ":womans_hat:" :codepoint "\x1f452" :description "womans hat")
    (:key ":athletic_shoe:" :codepoint "\x1f45f" :description "athletic shoe")
    (:key ":mans_shoe:" :codepoint "\x1f45e" :description "mans shoe")
    (:key ":sandal:" :codepoint "\x1f461" :description "womans sandal")
    (:key ":high_heel:" :codepoint "\x1f460" :description "high-heeled shoe")
    (:key ":boot:" :codepoint "\x1f462" :description "womans boots")
    (:key ":shirt:" :codepoint "\x1f455" :description "t-shirt")
    (:key ":necktie:" :codepoint "\x1f454" :description "necktie")
    (:key ":womans_clothes:" :codepoint "\x1f45a" :description "womans clothes")
    (:key ":dress:" :codepoint "\x1f457" :description "dress")
    (:key ":running_shirt_with_sash:" :codepoint "\x1f3bd" :description "running shirt with sash")
    (:key ":jeans:" :codepoint "\x1f456" :description "jeans")
    (:key ":kimono:" :codepoint "\x1f458" :description "kimono")
    (:key ":bikini:" :codepoint "\x1f459" :description "bikini")
    (:key ":briefcase:" :codepoint "\x1f4bc" :description "briefcase")
    (:key ":handbag:" :codepoint "\x1f45c" :description "handbag")
    (:key ":pouch:" :codepoint "\x1f45d" :description "pouch")
    (:key ":purse:" :codepoint "\x1f45b" :description "purse")
    (:key ":eyeglasses:" :codepoint "\x1f453" :description "eyeglasses")
    (:key ":ribbon:" :codepoint "\x1f380" :description "ribbon")
    (:key ":closed_umbrella:" :codepoint "\x1f302" :description "closed umbrella")
    (:key ":lipstick:" :codepoint "\x1f484" :description "lipstick")
    (:key ":yellow_heart:" :codepoint "\x1f49b" :description "yellow heart")
    (:key ":blue_heart:" :codepoint "\x1f499" :description "blue heart")
    (:key ":purple_heart:" :codepoint "\x1f49c" :description "purple heart")
    (:key ":green_heart:" :codepoint "\x1f49a" :description "green heart")
    (:key ":heart:" :codepoint "\x2764" :description "heavy black heart")
    (:key ":broken_heart:" :codepoint "\x1f494" :description "broken heart")
    (:key ":heartpulse:" :codepoint "\x1f497" :description "growing heart")
    (:key ":heartbeat:" :codepoint "\x1f493" :description "beating heart")
    (:key ":two_hearts:" :codepoint "\x1f495" :description "two hearts")
    (:key ":sparkling_heart:" :codepoint "\x1f496" :description "sparkling heart")
    (:key ":revolving_hearts:" :codepoint "\x1f49e" :description "revolving hearts")
    (:key ":cupid:" :codepoint "\x1f498" :description "heart with arrow")
    (:key ":love_letter:" :codepoint "\x1f48c" :description "love letter")
    (:key ":kiss:" :codepoint "\x1f48b" :description "kiss mark")
    (:key ":ring:" :codepoint "\x1f48d" :description "ring")
    (:key ":gem:" :codepoint "\x1f48e" :description "gem stone")
    (:key ":bust_in_silhouette:" :codepoint "\x1f464" :description "bust in silhouette")
    (:key ":busts_in_silhouette:" :codepoint "\x1f465" :description "busts in silhouette")
    (:key ":speech_balloon:" :codepoint "\x1f4ac" :description "speech balloon")
    (:key ":footprints:" :codepoint "\x1f463" :description "footprints")
    (:key ":thought_balloon:" :codepoint "\x1f4ad" :description "thought balloon")
    (:key ":dog:" :codepoint "\x1f436" :description "dog face")
    (:key ":wolf:" :codepoint "\x1f43a" :description "wolf face")
    (:key ":cat:" :codepoint "\x1f431" :description "cat face")
    (:key ":mouse:" :codepoint "\x1f42d" :description "mouse face")
    (:key ":hamster:" :codepoint "\x1f439" :description "hamster face")
    (:key ":rabbit:" :codepoint "\x1f430" :description "rabbit face")
    (:key ":frog:" :codepoint "\x1f438" :description "frog face")
    (:key ":tiger:" :codepoint "\x1f42f" :description "tiger face")
    (:key ":koala:" :codepoint "\x1f428" :description "koala")
    (:key ":bear:" :codepoint "\x1f43b" :description "bear face")
    (:key ":pig:" :codepoint "\x1f437" :description "pig face")
    (:key ":pig_nose:" :codepoint "\x1f43d" :description "pig nose")
    (:key ":cow:" :codepoint "\x1f42e" :description "cow face")
    (:key ":boar:" :codepoint "\x1f417" :description "boar")
    (:key ":monkey_face:" :codepoint "\x1f435" :description "monkey face")
    (:key ":monkey:" :codepoint "\x1f412" :description "monkey")
    (:key ":horse:" :codepoint "\x1f434" :description "horse face")
    (:key ":sheep:" :codepoint "\x1f411" :description "sheep")
    (:key ":elephant:" :codepoint "\x1f418" :description "elephant")
    (:key ":panda_face:" :codepoint "\x1f43c" :description "panda face")
    (:key ":penguin:" :codepoint "\x1f427" :description "penguin")
    (:key ":bird:" :codepoint "\x1f426" :description "bird")
    (:key ":baby_chick:" :codepoint "\x1f424" :description "baby chick")
    (:key ":hatched_chick:" :codepoint "\x1f425" :description "front-facing baby chick")
    (:key ":hatching_chick:" :codepoint "\x1f423" :description "hatching chick")
    (:key ":chicken:" :codepoint "\x1f414" :description "chicken")
    (:key ":snake:" :codepoint "\x1f40d" :description "snake")
    (:key ":turtle:" :codepoint "\x1f422" :description "turtle")
    (:key ":bug:" :codepoint "\x1f41b" :description "bug")
    (:key ":bee:" :codepoint "\x1f41d" :description "honeybee")
    (:key ":ant:" :codepoint "\x1f41c" :description "ant")
    (:key ":beetle:" :codepoint "\x1f41e" :description "lady beetle")
    (:key ":snail:" :codepoint "\x1f40c" :description "snail")
    (:key ":octopus:" :codepoint "\x1f419" :description "octopus")
    (:key ":shell:" :codepoint "\x1f41a" :description "spiral shell")
    (:key ":tropical_fish:" :codepoint "\x1f420" :description "tropical fish")
    (:key ":fish:" :codepoint "\x1f41f" :description "fish")
    (:key ":dolphin:" :codepoint "\x1f42c" :description "dolphin")
    (:key ":whale:" :codepoint "\x1f433" :description "spouting whale")
    (:key ":whale2:" :codepoint "\x1f40b" :description "whale")
    (:key ":cow2:" :codepoint "\x1f404" :description "cow")
    (:key ":ram:" :codepoint "\x1f40f" :description "ram")
    (:key ":rat:" :codepoint "\x1f400" :description "rat")
    (:key ":water_buffalo:" :codepoint "\x1f403" :description "water buffalo")
    (:key ":tiger2:" :codepoint "\x1f405" :description "tiger")
    (:key ":rabbit2:" :codepoint "\x1f407" :description "rabbit")
    (:key ":dragon:" :codepoint "\x1f409" :description "dragon")
    (:key ":racehorse:" :codepoint "\x1f40e" :description "horse")
    (:key ":goat:" :codepoint "\x1f410" :description "goat")
    (:key ":rooster:" :codepoint "\x1f413" :description "rooster")
    (:key ":dog2:" :codepoint "\x1f415" :description "dog")
    (:key ":pig2:" :codepoint "\x1f416" :description "pig")
    (:key ":mouse2:" :codepoint "\x1f401" :description "mouse")
    (:key ":ox:" :codepoint "\x1f402" :description "ox")
    (:key ":dragon_face:" :codepoint "\x1f432" :description "dragon face")
    (:key ":blowfish:" :codepoint "\x1f421" :description "blowfish")
    (:key ":crocodile:" :codepoint "\x1f40a" :description "crocodile")
    (:key ":camel:" :codepoint "\x1f42b" :description "bactrian camel")
    (:key ":dromedary_camel:" :codepoint "\x1f42a" :description "dromedary camel")
    (:key ":leopard:" :codepoint "\x1f406" :description "leopard")
    (:key ":cat2:" :codepoint "\x1f408" :description "cat")
    (:key ":poodle:" :codepoint "\x1f429" :description "poodle")
    (:key ":feet:" :codepoint "\x1f43e" :description "paw prints")
    (:key ":bouquet:" :codepoint "\x1f490" :description "bouquet")
    (:key ":cherry_blossom:" :codepoint "\x1f338" :description "cherry blossom")
    (:key ":tulip:" :codepoint "\x1f337" :description "tulip")
    (:key ":four_leaf_clover:" :codepoint "\x1f340" :description "four leaf clover")
    (:key ":rose:" :codepoint "\x1f339" :description "rose")
    (:key ":sunflower:" :codepoint "\x1f33b" :description "sunflower")
    (:key ":hibiscus:" :codepoint "\x1f33a" :description "hibiscus")
    (:key ":maple_leaf:" :codepoint "\x1f341" :description "maple leaf")
    (:key ":leaves:" :codepoint "\x1f343" :description "leaf fluttering in wind")
    (:key ":fallen_leaf:" :codepoint "\x1f342" :description "fallen leaf")
    (:key ":herb:" :codepoint "\x1f33f" :description "herb")
    (:key ":ear_of_rice:" :codepoint "\x1f33e" :description "ear of rice")
    (:key ":mushroom:" :codepoint "\x1f344" :description "mushroom")
    (:key ":cactus:" :codepoint "\x1f335" :description "cactus")
    (:key ":palm_tree:" :codepoint "\x1f334" :description "palm tree")
    (:key ":evergreen_tree:" :codepoint "\x1f332" :description "evergreen tree")
    (:key ":deciduous_tree:" :codepoint "\x1f333" :description "deciduous tree")
    (:key ":chestnut:" :codepoint "\x1f330" :description "chestnut")
    (:key ":seedling:" :codepoint "\x1f331" :description "seedling")
    (:key ":blossom:" :codepoint "\x1f33c" :description "blossom")
    (:key ":globe_with_meridians:" :codepoint "\x1f310" :description "globe with meridians")
    (:key ":sun_with_face:" :codepoint "\x1f31e" :description "sun with face")
    (:key ":full_moon_with_face:" :codepoint "\x1f31d" :description "full moon with face")
    (:key ":new_moon_with_face:" :codepoint "\x1f31a" :description "new moon with face")
    (:key ":new_moon:" :codepoint "\x1f311" :description "new moon symbol")
    (:key ":waxing_crescent_moon:" :codepoint "\x1f312" :description "waxing crescent moon symbol")
    (:key ":first_quarter_moon:" :codepoint "\x1f313" :description "first quarter moon symbol")
    (:key ":moon:" :codepoint "\x1f314" :description "waxing gibbous moon symbol")
    (:key ":full_moon:" :codepoint "\x1f315" :description "full moon symbol")
    (:key ":waning_gibbous_moon:" :codepoint "\x1f316" :description "waning gibbous moon symbol")
    (:key ":last_quarter_moon:" :codepoint "\x1f317" :description "last quarter moon symbol")
    (:key ":waning_crescent_moon:" :codepoint "\x1f318" :description "waning crescent moon symbol")
    (:key ":last_quarter_moon_with_face:" :codepoint "\x1f31c" :description "last quarter moon with face")
    (:key ":first_quarter_moon_with_face:" :codepoint "\x1f31b" :description "first quarter moon with face")
    (:key ":crescent_moon:" :codepoint "\x1f319" :description "crescent moon")
    (:key ":earth_africa:" :codepoint "\x1f30d" :description "earth globe europe-africa")
    (:key ":earth_americas:" :codepoint "\x1f30e" :description "earth globe americas")
    (:key ":earth_asia:" :codepoint "\x1f30f" :description "earth globe asia-australia")
    (:key ":volcano:" :codepoint "\x1f30b" :description "volcano")
    (:key ":milky_way:" :codepoint "\x1f30c" :description "milky way")
    (:key ":stars:" :codepoint "\x1f320" :description "shooting star")
    (:key ":star:" :codepoint "\x2b50" :description "white medium star")
    (:key ":sunny:" :codepoint "\x2600" :description "black sun with rays")
    (:key ":partly_sunny:" :codepoint "\x26c5" :description "sun behind cloud")
    (:key ":cloud:" :codepoint "\x2601" :description "cloud")
    (:key ":zap:" :codepoint "\x26a1" :description "high voltage sign")
    (:key ":umbrella:" :codepoint "\x2614" :description "umbrella with rain drops")
    (:key ":snowflake:" :codepoint "\x2744" :description "snowflake")
    (:key ":snowman:" :codepoint "\x26c4" :description "snowman without snow")
    (:key ":cyclone:" :codepoint "\x1f300" :description "cyclone")
    (:key ":foggy:" :codepoint "\x1f301" :description "foggy")
    (:key ":rainbow:" :codepoint "\x1f308" :description "rainbow")
    (:key ":ocean:" :codepoint "\x1f30a" :description "water wave")
    (:key ":bamboo:" :codepoint "\x1f38d" :description "pine decoration")
    (:key ":gift_heart:" :codepoint "\x1f49d" :description "heart with ribbon")
    (:key ":dolls:" :codepoint "\x1f38e" :description "japanese dolls")
    (:key ":school_satchel:" :codepoint "\x1f392" :description "school satchel")
    (:key ":mortar_board:" :codepoint "\x1f393" :description "graduation cap")
    (:key ":flags:" :codepoint "\x1f38f" :description "carp streamer")
    (:key ":fireworks:" :codepoint "\x1f386" :description "fireworks")
    (:key ":sparkler:" :codepoint "\x1f387" :description "firework sparkler")
    (:key ":wind_chime:" :codepoint "\x1f390" :description "wind chime")
    (:key ":rice_scene:" :codepoint "\x1f391" :description "moon viewing ceremony")
    (:key ":jack_o_lantern:" :codepoint "\x1f383" :description "jack-o-lantern")
    (:key ":ghost:" :codepoint "\x1f47b" :description "ghost")
    (:key ":santa:" :codepoint "\x1f385" :description "father christmas")
    (:key ":christmas_tree:" :codepoint "\x1f384" :description "christmas tree")
    (:key ":gift:" :codepoint "\x1f381" :description "wrapped present")
    (:key ":tanabata_tree:" :codepoint "\x1f38b" :description "tanabata tree")
    (:key ":tada:" :codepoint "\x1f389" :description "party popper")
    (:key ":confetti_ball:" :codepoint "\x1f38a" :description "confetti ball")
    (:key ":balloon:" :codepoint "\x1f388" :description "balloon")
    (:key ":crossed_flags:" :codepoint "\x1f38c" :description "crossed flags")
    (:key ":crystal_ball:" :codepoint "\x1f52e" :description "crystal ball")
    (:key ":movie_camera:" :codepoint "\x1f3a5" :description "movie camera")
    (:key ":camera:" :codepoint "\x1f4f7" :description "camera")
    (:key ":video_camera:" :codepoint "\x1f4f9" :description "video camera")
    (:key ":vhs:" :codepoint "\x1f4fc" :description "videocassette")
    (:key ":cd:" :codepoint "\x1f4bf" :description "optical disc")
    (:key ":dvd:" :codepoint "\x1f4c0" :description "dvd")
    (:key ":minidisc:" :codepoint "\x1f4bd" :description "minidisc")
    (:key ":floppy_disk:" :codepoint "\x1f4be" :description "floppy disk")
    (:key ":computer:" :codepoint "\x1f4bb" :description "personal computer")
    (:key ":iphone:" :codepoint "\x1f4f1" :description "mobile phone")
    (:key ":phone:" :codepoint "\x260e" :description "black telephone")
    (:key ":telephone_receiver:" :codepoint "\x1f4de" :description "telephone receiver")
    (:key ":pager:" :codepoint "\x1f4df" :description "pager")
    (:key ":fax:" :codepoint "\x1f4e0" :description "fax machine")
    (:key ":satellite:" :codepoint "\x1f4e1" :description "satellite antenna")
    (:key ":tv:" :codepoint "\x1f4fa" :description "television")
    (:key ":radio:" :codepoint "\x1f4fb" :description "radio")
    (:key ":loud_sound:" :codepoint "\x1f50a" :description "speaker with three sound waves")
    (:key ":sound:" :codepoint "\x1f509" :description "speaker with one sound wave")
    (:key ":speaker:" :codepoint "\x1f508" :description "speaker")
    (:key ":mute:" :codepoint "\x1f507" :description "speaker with cancellation stroke")
    (:key ":bell:" :codepoint "\x1f514" :description "bell")
    (:key ":no_bell:" :codepoint "\x1f515" :description "bell with cancellation stroke")
    (:key ":loudspeaker:" :codepoint "\x1f4e2" :description "public address loudspeaker")
    (:key ":mega:" :codepoint "\x1f4e3" :description "cheering megaphone")
    (:key ":hourglass_flowing_sand:" :codepoint "\x23f3" :description "hourglass with flowing sand")
    (:key ":hourglass:" :codepoint "\x231b" :description "hourglass")
    (:key ":alarm_clock:" :codepoint "\x23f0" :description "alarm clock")
    (:key ":watch:" :codepoint "\x231a" :description "watch")
    (:key ":unlock:" :codepoint "\x1f513" :description "open lock")
    (:key ":lock:" :codepoint "\x1f512" :description "lock")
    (:key ":lock_with_ink_pen:" :codepoint "\x1f50f" :description "lock with ink pen")
    (:key ":closed_lock_with_key:" :codepoint "\x1f510" :description "closed lock with key")
    (:key ":key:" :codepoint "\x1f511" :description "key")
    (:key ":mag_right:" :codepoint "\x1f50e" :description "right-pointing magnifying glass")
    (:key ":bulb:" :codepoint "\x1f4a1" :description "electric light bulb")
    (:key ":flashlight:" :codepoint "\x1f526" :description "electric torch")
    (:key ":high_brightness:" :codepoint "\x1f506" :description "high brightness symbol")
    (:key ":low_brightness:" :codepoint "\x1f505" :description "low brightness symbol")
    (:key ":electric_plug:" :codepoint "\x1f50c" :description "electric plug")
    (:key ":battery:" :codepoint "\x1f50b" :description "battery")
    (:key ":mag:" :codepoint "\x1f50d" :description "left-pointing magnifying glass")
    (:key ":bathtub:" :codepoint "\x1f6c1" :description "bathtub")
    (:key ":bath:" :codepoint "\x1f6c0" :description "bath")
    (:key ":shower:" :codepoint "\x1f6bf" :description "shower")
    (:key ":toilet:" :codepoint "\x1f6bd" :description "toilet")
    (:key ":wrench:" :codepoint "\x1f527" :description "wrench")
    (:key ":nut_and_bolt:" :codepoint "\x1f529" :description "nut and bolt")
    (:key ":hammer:" :codepoint "\x1f528" :description "hammer")
    (:key ":door:" :codepoint "\x1f6aa" :description "door")
    (:key ":smoking:" :codepoint "\x1f6ac" :description "smoking symbol")
    (:key ":bomb:" :codepoint "\x1f4a3" :description "bomb")
    (:key ":gun:" :codepoint "\x1f52b" :description "pistol")
    (:key ":hocho:" :codepoint "\x1f52a" :description "hocho")
    (:key ":pill:" :codepoint "\x1f48a" :description "pill")
    (:key ":syringe:" :codepoint "\x1f489" :description "syringe")
    (:key ":moneybag:" :codepoint "\x1f4b0" :description "money bag")
    (:key ":yen:" :codepoint "\x1f4b4" :description "banknote with yen sign")
    (:key ":dollar:" :codepoint "\x1f4b5" :description "banknote with dollar sign")
    (:key ":pound:" :codepoint "\x1f4b7" :description "banknote with pound sign")
    (:key ":euro:" :codepoint "\x1f4b6" :description "banknote with euro sign")
    (:key ":credit_card:" :codepoint "\x1f4b3" :description "credit card")
    (:key ":money_with_wings:" :codepoint "\x1f4b8" :description "money with wings")
    (:key ":calling:" :codepoint "\x1f4f2" :description "mobile phone with rightwards arrow at left")
    (:key ":e-mail:" :codepoint "\x1f4e7" :description "e-mail symbol")
    (:key ":inbox_tray:" :codepoint "\x1f4e5" :description "inbox tray")
    (:key ":outbox_tray:" :codepoint "\x1f4e4" :description "outbox tray")
    (:key ":email:" :codepoint "\x2709" :description "envelope")
    (:key ":envelope_with_arrow:" :codepoint "\x1f4e9" :description "envelope with downwards arrow above")
    (:key ":incoming_envelope:" :codepoint "\x1f4e8" :description "incoming envelope")
    (:key ":postal_horn:" :codepoint "\x1f4ef" :description "postal horn")
    (:key ":mailbox:" :codepoint "\x1f4eb" :description "closed mailbox with raised flag")
    (:key ":mailbox_closed:" :codepoint "\x1f4ea" :description "closed mailbox with lowered flag")
    (:key ":mailbox_with_mail:" :codepoint "\x1f4ec" :description "open mailbox with raised flag")
    (:key ":mailbox_with_no_mail:" :codepoint "\x1f4ed" :description "open mailbox with lowered flag")
    (:key ":postbox:" :codepoint "\x1f4ee" :description "postbox")
    (:key ":package:" :codepoint "\x1f4e6" :description "package")
    (:key ":memo:" :codepoint "\x1f4dd" :description "memo")
    (:key ":page_facing_up:" :codepoint "\x1f4c4" :description "page facing up")
    (:key ":page_with_curl:" :codepoint "\x1f4c3" :description "page with curl")
    (:key ":bookmark_tabs:" :codepoint "\x1f4d1" :description "bookmark tabs")
    (:key ":bar_chart:" :codepoint "\x1f4ca" :description "bar chart")
    (:key ":chart_with_upwards_trend:" :codepoint "\x1f4c8" :description "chart with upwards trend")
    (:key ":chart_with_downwards_trend:" :codepoint "\x1f4c9" :description "chart with downwards trend")
    (:key ":scroll:" :codepoint "\x1f4dc" :description "scroll")
    (:key ":clipboard:" :codepoint "\x1f4cb" :description "clipboard")
    (:key ":date:" :codepoint "\x1f4c5" :description "calendar")
    (:key ":calendar:" :codepoint "\x1f4c6" :description "tear-off calendar")
    (:key ":card_index:" :codepoint "\x1f4c7" :description "card index")
    (:key ":file_folder:" :codepoint "\x1f4c1" :description "file folder")
    (:key ":open_file_folder:" :codepoint "\x1f4c2" :description "open file folder")
    (:key ":scissors:" :codepoint "\x2702" :description "black scissors")
    (:key ":pushpin:" :codepoint "\x1f4cc" :description "pushpin")
    (:key ":paperclip:" :codepoint "\x1f4ce" :description "paperclip")
    (:key ":black_nib:" :codepoint "\x2712" :description "black nib")
    (:key ":pencil2:" :codepoint "\x270f" :description "pencil")
    (:key ":straight_ruler:" :codepoint "\x1f4cf" :description "straight ruler")
    (:key ":triangular_ruler:" :codepoint "\x1f4d0" :description "triangular ruler")
    (:key ":closed_book:" :codepoint "\x1f4d5" :description "closed book")
    (:key ":green_book:" :codepoint "\x1f4d7" :description "green book")
    (:key ":blue_book:" :codepoint "\x1f4d8" :description "blue book")
    (:key ":orange_book:" :codepoint "\x1f4d9" :description "orange book")
    (:key ":notebook:" :codepoint "\x1f4d3" :description "notebook")
    (:key ":notebook_with_decorative_cover:" :codepoint "\x1f4d4" :description "notebook with decorative cover")
    (:key ":ledger:" :codepoint "\x1f4d2" :description "ledger")
    (:key ":books:" :codepoint "\x1f4da" :description "books")
    (:key ":book:" :codepoint "\x1f4d6" :description "open book")
    (:key ":bookmark:" :codepoint "\x1f516" :description "bookmark")
    (:key ":name_badge:" :codepoint "\x1f4db" :description "name badge")
    (:key ":microscope:" :codepoint "\x1f52c" :description "microscope")
    (:key ":telescope:" :codepoint "\x1f52d" :description "telescope")
    (:key ":newspaper:" :codepoint "\x1f4f0" :description "newspaper")
    (:key ":art:" :codepoint "\x1f3a8" :description "artist palette")
    (:key ":clapper:" :codepoint "\x1f3ac" :description "clapper board")
    (:key ":microphone:" :codepoint "\x1f3a4" :description "microphone")
    (:key ":headphones:" :codepoint "\x1f3a7" :description "headphone")
    (:key ":musical_score:" :codepoint "\x1f3bc" :description "musical score")
    (:key ":musical_note:" :codepoint "\x1f3b5" :description "musical note")
    (:key ":notes:" :codepoint "\x1f3b6" :description "multiple musical notes")
    (:key ":musical_keyboard:" :codepoint "\x1f3b9" :description "musical keyboard")
    (:key ":violin:" :codepoint "\x1f3bb" :description "violin")
    (:key ":trumpet:" :codepoint "\x1f3ba" :description "trumpet")
    (:key ":saxophone:" :codepoint "\x1f3b7" :description "saxophone")
    (:key ":guitar:" :codepoint "\x1f3b8" :description "guitar")
    (:key ":space_invader:" :codepoint "\x1f47e" :description "alien monster")
    (:key ":video_game:" :codepoint "\x1f3ae" :description "video game")
    (:key ":black_joker:" :codepoint "\x1f0cf" :description "playing card black joker")
    (:key ":flower_playing_cards:" :codepoint "\x1f3b4" :description "flower playing cards")
    (:key ":mahjong:" :codepoint "\x1f004" :description "mahjong tile red dragon")
    (:key ":game_die:" :codepoint "\x1f3b2" :description "game die")
    (:key ":dart:" :codepoint "\x1f3af" :description "direct hit")
    (:key ":football:" :codepoint "\x1f3c8" :description "american football")
    (:key ":basketball:" :codepoint "\x1f3c0" :description "basketball and hoop")
    (:key ":soccer:" :codepoint "\x26bd" :description "soccer ball")
    (:key ":baseball:" :codepoint "\x26be" :description "baseball")
    (:key ":tennis:" :codepoint "\x1f3be" :description "tennis racquet and ball")
    (:key ":8ball:" :codepoint "\x1f3b1" :description "billiards")
    (:key ":rugby_football:" :codepoint "\x1f3c9" :description "rugby football")
    (:key ":bowling:" :codepoint "\x1f3b3" :description "bowling")
    (:key ":golf:" :codepoint "\x26f3" :description "flag in hole")
    (:key ":mountain_bicyclist:" :codepoint "\x1f6b5" :description "mountain bicyclist")
    (:key ":bicyclist:" :codepoint "\x1f6b4" :description "bicyclist")
    (:key ":checkered_flag:" :codepoint "\x1f3c1" :description "chequered flag")
    (:key ":horse_racing:" :codepoint "\x1f3c7" :description "horse racing")
    (:key ":trophy:" :codepoint "\x1f3c6" :description "trophy")
    (:key ":ski:" :codepoint "\x1f3bf" :description "ski and ski boot")
    (:key ":snowboarder:" :codepoint "\x1f3c2" :description "snowboarder")
    (:key ":swimmer:" :codepoint "\x1f3ca" :description "swimmer")
    (:key ":surfer:" :codepoint "\x1f3c4" :description "surfer")
    (:key ":fishing_pole_and_fish:" :codepoint "\x1f3a3" :description "fishing pole and fish")
    (:key ":coffee:" :codepoint "\x2615" :description "hot beverage")
    (:key ":tea:" :codepoint "\x1f375" :description "teacup without handle")
    (:key ":sake:" :codepoint "\x1f376" :description "sake bottle and cup")
    (:key ":baby_bottle:" :codepoint "\x1f37c" :description "baby bottle")
    (:key ":beer:" :codepoint "\x1f37a" :description "beer mug")
    (:key ":beers:" :codepoint "\x1f37b" :description "clinking beer mugs")
    (:key ":cocktail:" :codepoint "\x1f378" :description "cocktail glass")
    (:key ":tropical_drink:" :codepoint "\x1f379" :description "tropical drink")
    (:key ":wine_glass:" :codepoint "\x1f377" :description "wine glass")
    (:key ":fork_and_knife:" :codepoint "\x1f374" :description "fork and knife")
    (:key ":pizza:" :codepoint "\x1f355" :description "slice of pizza")
    (:key ":hamburger:" :codepoint "\x1f354" :description "hamburger")
    (:key ":fries:" :codepoint "\x1f35f" :description "french fries")
    (:key ":poultry_leg:" :codepoint "\x1f357" :description "poultry leg")
    (:key ":meat_on_bone:" :codepoint "\x1f356" :description "meat on bone")
    (:key ":spaghetti:" :codepoint "\x1f35d" :description "spaghetti")
    (:key ":curry:" :codepoint "\x1f35b" :description "curry and rice")
    (:key ":fried_shrimp:" :codepoint "\x1f364" :description "fried shrimp")
    (:key ":bento:" :codepoint "\x1f371" :description "bento box")
    (:key ":sushi:" :codepoint "\x1f363" :description "sushi")
    (:key ":fish_cake:" :codepoint "\x1f365" :description "fish cake with swirl design")
    (:key ":rice_ball:" :codepoint "\x1f359" :description "rice ball")
    (:key ":rice_cracker:" :codepoint "\x1f358" :description "rice cracker")
    (:key ":rice:" :codepoint "\x1f35a" :description "cooked rice")
    (:key ":ramen:" :codepoint "\x1f35c" :description "steaming bowl")
    (:key ":stew:" :codepoint "\x1f372" :description "pot of food")
    (:key ":oden:" :codepoint "\x1f362" :description "oden")
    (:key ":dango:" :codepoint "\x1f361" :description "dango")
    (:key ":egg:" :codepoint "\x1f373" :description "cooking")
    (:key ":bread:" :codepoint "\x1f35e" :description "bread")
    (:key ":doughnut:" :codepoint "\x1f369" :description "doughnut")
    (:key ":custard:" :codepoint "\x1f36e" :description "custard")
    (:key ":icecream:" :codepoint "\x1f366" :description "soft ice cream")
    (:key ":ice_cream:" :codepoint "\x1f368" :description "ice cream")
    (:key ":shaved_ice:" :codepoint "\x1f367" :description "shaved ice")
    (:key ":birthday:" :codepoint "\x1f382" :description "birthday cake")
    (:key ":cake:" :codepoint "\x1f370" :description "shortcake")
    (:key ":cookie:" :codepoint "\x1f36a" :description "cookie")
    (:key ":chocolate_bar:" :codepoint "\x1f36b" :description "chocolate bar")
    (:key ":candy:" :codepoint "\x1f36c" :description "candy")
    (:key ":lollipop:" :codepoint "\x1f36d" :description "lollipop")
    (:key ":honey_pot:" :codepoint "\x1f36f" :description "honey pot")
    (:key ":apple:" :codepoint "\x1f34e" :description "red apple")
    (:key ":green_apple:" :codepoint "\x1f34f" :description "green apple")
    (:key ":tangerine:" :codepoint "\x1f34a" :description "tangerine")
    (:key ":lemon:" :codepoint "\x1f34b" :description "lemon")
    (:key ":cherries:" :codepoint "\x1f352" :description "cherries")
    (:key ":grapes:" :codepoint "\x1f347" :description "grapes")
    (:key ":watermelon:" :codepoint "\x1f349" :description "watermelon")
    (:key ":strawberry:" :codepoint "\x1f353" :description "strawberry")
    (:key ":peach:" :codepoint "\x1f351" :description "peach")
    (:key ":melon:" :codepoint "\x1f348" :description "melon")
    (:key ":banana:" :codepoint "\x1f34c" :description "banana")
    (:key ":pear:" :codepoint "\x1f350" :description "pear")
    (:key ":pineapple:" :codepoint "\x1f34d" :description "pineapple")
    (:key ":sweet_potato:" :codepoint "\x1f360" :description "roasted sweet potato")
    (:key ":eggplant:" :codepoint "\x1f346" :description "aubergine")
    (:key ":tomato:" :codepoint "\x1f345" :description "tomato")
    (:key ":corn:" :codepoint "\x1f33d" :description "ear of maize")
    (:key ":house:" :codepoint "\x1f3e0" :description "house building")
    (:key ":house_with_garden:" :codepoint "\x1f3e1" :description "house with garden")
    (:key ":school:" :codepoint "\x1f3eb" :description "school")
    (:key ":office:" :codepoint "\x1f3e2" :description "office building")
    (:key ":post_office:" :codepoint "\x1f3e3" :description "japanese post office")
    (:key ":hospital:" :codepoint "\x1f3e5" :description "hospital")
    (:key ":bank:" :codepoint "\x1f3e6" :description "bank")
    (:key ":convenience_store:" :codepoint "\x1f3ea" :description "convenience store")
    (:key ":love_hotel:" :codepoint "\x1f3e9" :description "love hotel")
    (:key ":hotel:" :codepoint "\x1f3e8" :description "hotel")
    (:key ":wedding:" :codepoint "\x1f492" :description "wedding")
    (:key ":church:" :codepoint "\x26ea" :description "church")
    (:key ":department_store:" :codepoint "\x1f3ec" :description "department store")
    (:key ":european_post_office:" :codepoint "\x1f3e4" :description "european post office")
    (:key ":city_sunrise:" :codepoint "\x1f307" :description "sunset over buildings")
    (:key ":city_sunset:" :codepoint "\x1f306" :description "cityscape at dusk")
    (:key ":japanese_castle:" :codepoint "\x1f3ef" :description "japanese castle")
    (:key ":european_castle:" :codepoint "\x1f3f0" :description "european castle")
    (:key ":tent:" :codepoint "\x26fa" :description "tent")
    (:key ":factory:" :codepoint "\x1f3ed" :description "factory")
    (:key ":tokyo_tower:" :codepoint "\x1f5fc" :description "tokyo tower")
    (:key ":japan:" :codepoint "\x1f5fe" :description "silhouette of japan")
    (:key ":mount_fuji:" :codepoint "\x1f5fb" :description "mount fuji")
    (:key ":sunrise_over_mountains:" :codepoint "\x1f304" :description "sunrise over mountains")
    (:key ":sunrise:" :codepoint "\x1f305" :description "sunrise")
    (:key ":night_with_stars:" :codepoint "\x1f303" :description "night with stars")
    (:key ":statue_of_liberty:" :codepoint "\x1f5fd" :description "statue of liberty")
    (:key ":bridge_at_night:" :codepoint "\x1f309" :description "bridge at night")
    (:key ":carousel_horse:" :codepoint "\x1f3a0" :description "carousel horse")
    (:key ":ferris_wheel:" :codepoint "\x1f3a1" :description "ferris wheel")
    (:key ":fountain:" :codepoint "\x26f2" :description "fountain")
    (:key ":roller_coaster:" :codepoint "\x1f3a2" :description "roller coaster")
    (:key ":ship:" :codepoint "\x1f6a2" :description "ship")
    (:key ":boat:" :codepoint "\x26f5" :description "sailboat")
    (:key ":speedboat:" :codepoint "\x1f6a4" :description "speedboat")
    (:key ":rowboat:" :codepoint "\x1f6a3" :description "rowboat")
    (:key ":anchor:" :codepoint "\x2693" :description "anchor")
    (:key ":rocket:" :codepoint "\x1f680" :description "rocket")
    (:key ":airplane:" :codepoint "\x2708" :description "airplane")
    (:key ":seat:" :codepoint "\x1f4ba" :description "seat")
    (:key ":helicopter:" :codepoint "\x1f681" :description "helicopter")
    (:key ":steam_locomotive:" :codepoint "\x1f682" :description "steam locomotive")
    (:key ":tram:" :codepoint "\x1f68a" :description "tram")
    (:key ":station:" :codepoint "\x1f689" :description "station")
    (:key ":mountain_railway:" :codepoint "\x1f69e" :description "mountain railway")
    (:key ":train2:" :codepoint "\x1f686" :description "train")
    (:key ":bullettrain_side:" :codepoint "\x1f684" :description "high-speed train")
    (:key ":bullettrain_front:" :codepoint "\x1f685" :description "high-speed train with bullet nose")
    (:key ":light_rail:" :codepoint "\x1f688" :description "light rail")
    (:key ":metro:" :codepoint "\x1f687" :description "metro")
    (:key ":monorail:" :codepoint "\x1f69d" :description "monorail")
    (:key ":train:" :codepoint "\x1f68b" :description "tram car")
    (:key ":railway_car:" :codepoint "\x1f683" :description "railway car")
    (:key ":trolleybus:" :codepoint "\x1f68e" :description "trolleybus")
    (:key ":bus:" :codepoint "\x1f68c" :description "bus")
    (:key ":oncoming_bus:" :codepoint "\x1f68d" :description "oncoming bus")
    (:key ":blue_car:" :codepoint "\x1f699" :description "recreational vehicle")
    (:key ":oncoming_automobile:" :codepoint "\x1f698" :description "oncoming automobile")
    (:key ":car:" :codepoint "\x1f697" :description "automobile")
    (:key ":taxi:" :codepoint "\x1f695" :description "taxi")
    (:key ":oncoming_taxi:" :codepoint "\x1f696" :description "oncoming taxi")
    (:key ":articulated_lorry:" :codepoint "\x1f69b" :description "articulated lorry")
    (:key ":truck:" :codepoint "\x1f69a" :description "delivery truck")
    (:key ":rotating_light:" :codepoint "\x1f6a8" :description "police cars revolving light")
    (:key ":police_car:" :codepoint "\x1f693" :description "police car")
    (:key ":oncoming_police_car:" :codepoint "\x1f694" :description "oncoming police car")
    (:key ":fire_engine:" :codepoint "\x1f692" :description "fire engine")
    (:key ":ambulance:" :codepoint "\x1f691" :description "ambulance")
    (:key ":minibus:" :codepoint "\x1f690" :description "minibus")
    (:key ":bike:" :codepoint "\x1f6b2" :description "bicycle")
    (:key ":aerial_tramway:" :codepoint "\x1f6a1" :description "aerial tramway")
    (:key ":suspension_railway:" :codepoint "\x1f69f" :description "suspension railway")
    (:key ":mountain_cableway:" :codepoint "\x1f6a0" :description "mountain cableway")
    (:key ":tractor:" :codepoint "\x1f69c" :description "tractor")
    (:key ":barber:" :codepoint "\x1f488" :description "barber pole")
    (:key ":busstop:" :codepoint "\x1f68f" :description "bus stop")
    (:key ":ticket:" :codepoint "\x1f3ab" :description "ticket")
    (:key ":vertical_traffic_light:" :codepoint "\x1f6a6" :description "vertical traffic light")
    (:key ":traffic_light:" :codepoint "\x1f6a5" :description "horizontal traffic light")
    (:key ":warning:" :codepoint "\x26a0" :description "warning sign")
    (:key ":construction:" :codepoint "\x1f6a7" :description "construction sign")
    (:key ":beginner:" :codepoint "\x1f530" :description "japanese symbol for beginner")
    (:key ":fuelpump:" :codepoint "\x26fd" :description "fuel pump")
    (:key ":izakaya_lantern:" :codepoint "\x1f3ee" :description "izakaya lantern")
    (:key ":slot_machine:" :codepoint "\x1f3b0" :description "slot machine")
    (:key ":hotsprings:" :codepoint "\x2668" :description "hot springs")
    (:key ":moyai:" :codepoint "\x1f5ff" :description "moyai")
    (:key ":circus_tent:" :codepoint "\x1f3aa" :description "circus tent")
    (:key ":performing_arts:" :codepoint "\x1f3ad" :description "performing arts")
    (:key ":round_pushpin:" :codepoint "\x1f4cd" :description "round pushpin")
    (:key ":triangular_flag_on_post:" :codepoint "\x1f6a9" :description "triangular flag on post")
    (:key ":jp:" :codepoint "\x1f1ef" :description "regional indicator symbol letter j + regional indicator symbol letter p")
    (:key ":kr:" :codepoint "\x1f1f0" :description "regional indicator symbol letter k + regional indicator symbol letter r")
    (:key ":de:" :codepoint "\x1f1e9" :description "regional indicator symbol letter d + regional indicator symbol letter e")
    (:key ":cn:" :codepoint "\x1f1e8" :description "regional indicator symbol letter c + regional indicator symbol letter n")
    (:key ":us:" :codepoint "\x1f1fa" :description "regional indicator symbol letter u + regional indicator symbol letter s")
    (:key ":fr:" :codepoint "\x1f1eb" :description "regional indicator symbol letter f + regional indicator symbol letter r")
    (:key ":es:" :codepoint "\x1f1ea" :description "regional indicator symbol letter e + regional indicator symbol letter s")
    (:key ":it:" :codepoint "\x1f1ee" :description "regional indicator symbol letter i + regional indicator symbol letter t")
    (:key ":ru:" :codepoint "\x1f1f7" :description "regional indicator symbol letter r + regional indicator symbol letter u")
    (:key ":gb:" :codepoint "\x1f1ec" :description "regional indicator symbol letter g + regional indicator symbol letter b")
    (:key ":one:" :codepoint "\x31" :description "digit one + combining enclosing keycap")
    (:key ":two:" :codepoint "\x32" :description "digit two + combining enclosing keycap")
    (:key ":three:" :codepoint "\x33" :description "digit three + combining enclosing keycap")
    (:key ":four:" :codepoint "\x34" :description "digit four + combining enclosing keycap")
    (:key ":five:" :codepoint "\x35" :description "digit five + combining enclosing keycap")
    (:key ":six:" :codepoint "\x36" :description "digit six + combining enclosing keycap")
    (:key ":seven:" :codepoint "\x37" :description "digit seven + combining enclosing keycap")
    (:key ":eight:" :codepoint "\x38" :description "digit eight + combining enclosing keycap")
    (:key ":nine:" :codepoint "\x39" :description "digit nine + combining enclosing keycap")
    (:key ":zero:" :codepoint "\x30" :description "digit zero + combining enclosing keycap")
    (:key ":keycap_ten:" :codepoint "\x1f51f" :description "keycap ten")
    (:key ":1234:" :codepoint "\x1f522" :description "input symbol for numbers")
    (:key ":hash:" :codepoint "\x23" :description "number sign + combining enclosing keycap")
    (:key ":symbols:" :codepoint "\x1f523" :description "input symbol for symbols")
    (:key ":arrow_up:" :codepoint "\x2b06" :description "upwards black arrow")
    (:key ":arrow_down:" :codepoint "\x2b07" :description "downwards black arrow")
    (:key ":arrow_left:" :codepoint "\x2b05" :description "leftwards black arrow")
    (:key ":arrow_right:" :codepoint "\x27a1" :description "black rightwards arrow")
    (:key ":capital_abcd:" :codepoint "\x1f520" :description "input symbol for latin capital letters")
    (:key ":abcd:" :codepoint "\x1f521" :description "input symbol for latin small letters")
    (:key ":abc:" :codepoint "\x1f524" :description "input symbol for latin letters")
    (:key ":arrow_upper_right:" :codepoint "\x2197" :description "north east arrow")
    (:key ":arrow_upper_left:" :codepoint "\x2196" :description "north west arrow")
    (:key ":arrow_lower_right:" :codepoint "\x2198" :description "south east arrow")
    (:key ":arrow_lower_left:" :codepoint "\x2199" :description "south west arrow")
    (:key ":left_right_arrow:" :codepoint "\x2194" :description "left right arrow")
    (:key ":arrow_up_down:" :codepoint "\x2195" :description "up down arrow")
    (:key ":arrows_counterclockwise:" :codepoint "\x1f504" :description "anticlockwise downwards and upwards open circle arrows")
    (:key ":arrow_backward:" :codepoint "\x25c0" :description "black left-pointing triangle")
    (:key ":arrow_forward:" :codepoint "\x25b6" :description "black right-pointing triangle")
    (:key ":arrow_up_small:" :codepoint "\x1f53c" :description "up-pointing small red triangle")
    (:key ":arrow_down_small:" :codepoint "\x1f53d" :description "down-pointing small red triangle")
    (:key ":leftwards_arrow_with_hook:" :codepoint "\x21a9" :description "leftwards arrow with hook")
    (:key ":arrow_right_hook:" :codepoint "\x21aa" :description "rightwards arrow with hook")
    (:key ":information_source:" :codepoint "\x2139" :description "information source")
    (:key ":rewind:" :codepoint "\x23ea" :description "black left-pointing double triangle")
    (:key ":fast_forward:" :codepoint "\x23e9" :description "black right-pointing double triangle")
    (:key ":arrow_double_up:" :codepoint "\x23eb" :description "black up-pointing double triangle")
    (:key ":arrow_double_down:" :codepoint "\x23ec" :description "black down-pointing double triangle")
    (:key ":arrow_heading_down:" :codepoint "\x2935" :description "arrow pointing rightwards then curving downwards")
    (:key ":arrow_heading_up:" :codepoint "\x2934" :description "arrow pointing rightwards then curving upwards")
    (:key ":ok:" :codepoint "\x1f197" :description "squared ok")
    (:key ":twisted_rightwards_arrows:" :codepoint "\x1f500" :description "twisted rightwards arrows")
    (:key ":repeat:" :codepoint "\x1f501" :description "clockwise rightwards and leftwards open circle arrows")
    (:key ":repeat_one:" :codepoint "\x1f502" :description "clockwise rightwards and leftwards open circle arrows with circled one overlay")
    (:key ":new:" :codepoint "\x1f195" :description "squared new")
    (:key ":up:" :codepoint "\x1f199" :description "squared up with exclamation mark")
    (:key ":cool:" :codepoint "\x1f192" :description "squared cool")
    (:key ":free:" :codepoint "\x1f193" :description "squared free")
    (:key ":ng:" :codepoint "\x1f196" :description "squared ng")
    (:key ":signal_strength:" :codepoint "\x1f4f6" :description "antenna with bars")
    (:key ":cinema:" :codepoint "\x1f3a6" :description "cinema")
    (:key ":koko:" :codepoint "\x1f201" :description "squared katakana koko")
    (:key ":u6307:" :codepoint "\x1f22f" :description "squared cjk unified ideograph-6307")
    (:key ":u7a7a:" :codepoint "\x1f233" :description "squared cjk unified ideograph-7a7a")
    (:key ":u6e80:" :codepoint "\x1f235" :description "squared cjk unified ideograph-6e80")
    (:key ":u5408:" :codepoint "\x1f234" :description "squared cjk unified ideograph-5408")
    (:key ":u7981:" :codepoint "\x1f232" :description "squared cjk unified ideograph-7981")
    (:key ":ideograph_advantage:" :codepoint "\x1f250" :description "circled ideograph advantage")
    (:key ":u5272:" :codepoint "\x1f239" :description "squared cjk unified ideograph-5272")
    (:key ":u55b6:" :codepoint "\x1f23a" :description "squared cjk unified ideograph-55b6")
    (:key ":u6709:" :codepoint "\x1f236" :description "squared cjk unified ideograph-6709")
    (:key ":u7121:" :codepoint "\x1f21a" :description "squared cjk unified ideograph-7121")
    (:key ":restroom:" :codepoint "\x1f6bb" :description "restroom")
    (:key ":mens:" :codepoint "\x1f6b9" :description "mens symbol")
    (:key ":womens:" :codepoint "\x1f6ba" :description "womens symbol")
    (:key ":baby_symbol:" :codepoint "\x1f6bc" :description "baby symbol")
    (:key ":wc:" :codepoint "\x1f6be" :description "water closet")
    (:key ":potable_water:" :codepoint "\x1f6b0" :description "potable water symbol")
    (:key ":put_litter_in_its_place:" :codepoint "\x1f6ae" :description "put litter in its place symbol")
    (:key ":parking:" :codepoint "\x1f17f" :description "negative squared latin capital letter p")
    (:key ":wheelchair:" :codepoint "\x267f" :description "wheelchair symbol")
    (:key ":no_smoking:" :codepoint "\x1f6ad" :description "no smoking symbol")
    (:key ":u6708:" :codepoint "\x1f237" :description "squared cjk unified ideograph-6708")
    (:key ":u7533:" :codepoint "\x1f238" :description "squared cjk unified ideograph-7533")
    (:key ":sa:" :codepoint "\x1f202" :description "squared katakana sa")
    (:key ":m:" :codepoint "\x24c2" :description "circled latin capital letter m")
    (:key ":passport_control:" :codepoint "\x1f6c2" :description "passport control")
    (:key ":baggage_claim:" :codepoint "\x1f6c4" :description "baggage claim")
    (:key ":left_luggage:" :codepoint "\x1f6c5" :description "left luggage")
    (:key ":customs:" :codepoint "\x1f6c3" :description "customs")
    (:key ":accept:" :codepoint "\x1f251" :description "circled ideograph accept")
    (:key ":secret:" :codepoint "\x3299" :description "circled ideograph secret")
    (:key ":congratulations:" :codepoint "\x3297" :description "circled ideograph congratulation")
    (:key ":cl:" :codepoint "\x1f191" :description "squared cl")
    (:key ":sos:" :codepoint "\x1f198" :description "squared sos")
    (:key ":id:" :codepoint "\x1f194" :description "squared id")
    (:key ":no_entry_sign:" :codepoint "\x1f6ab" :description "no entry sign")
    (:key ":underage:" :codepoint "\x1f51e" :description "no one under eighteen symbol")
    (:key ":no_mobile_phones:" :codepoint "\x1f4f5" :description "no mobile phones")
    (:key ":do_not_litter:" :codepoint "\x1f6af" :description "do not litter symbol")
    (:key ":non-potable_water:" :codepoint "\x1f6b1" :description "non-potable water symbol")
    (:key ":no_bicycles:" :codepoint "\x1f6b3" :description "no bicycles")
    (:key ":no_pedestrians:" :codepoint "\x1f6b7" :description "no pedestrians")
    (:key ":children_crossing:" :codepoint "\x1f6b8" :description "children crossing")
    (:key ":no_entry:" :codepoint "\x26d4" :description "no entry")
    (:key ":eight_spoked_asterisk:" :codepoint "\x2733" :description "eight spoked asterisk")
    (:key ":sparkle:" :codepoint "\x2747" :description "sparkle")
    (:key ":negative_squared_cross_mark:" :codepoint "\x274e" :description "negative squared cross mark")
    (:key ":white_check_mark:" :codepoint "\x2705" :description "white heavy check mark")
    (:key ":eight_pointed_black_star:" :codepoint "\x2734" :description "eight pointed black star")
    (:key ":heart_decoration:" :codepoint "\x1f49f" :description "heart decoration")
    (:key ":vs:" :codepoint "\x1f19a" :description "squared vs")
    (:key ":vibration_mode:" :codepoint "\x1f4f3" :description "vibration mode")
    (:key ":mobile_phone_off:" :codepoint "\x1f4f4" :description "mobile phone off")
    (:key ":a:" :codepoint "\x1f170" :description "negative squared latin capital letter a")
    (:key ":b:" :codepoint "\x1f171" :description "negative squared latin capital letter b")
    (:key ":ab:" :codepoint "\x1f18e" :description "negative squared ab")
    (:key ":o2:" :codepoint "\x1f17e" :description "negative squared latin capital letter o")
    (:key ":diamond_shape_with_a_dot_inside:" :codepoint "\x1f4a0" :description "diamond shape with a dot inside")
    (:key ":loop:" :codepoint "\x27bf" :description "double curly loop")
    (:key ":recycle:" :codepoint "\x267b" :description "black universal recycling symbol")
    (:key ":aries:" :codepoint "\x2648" :description "aries")
    (:key ":taurus:" :codepoint "\x2649" :description "taurus")
    (:key ":gemini:" :codepoint "\x264a" :description "gemini")
    (:key ":cancer:" :codepoint "\x264b" :description "cancer")
    (:key ":leo:" :codepoint "\x264c" :description "leo")
    (:key ":virgo:" :codepoint "\x264d" :description "virgo")
    (:key ":libra:" :codepoint "\x264e" :description "libra")
    (:key ":scorpius:" :codepoint "\x264f" :description "scorpius")
    (:key ":sagittarius:" :codepoint "\x2650" :description "sagittarius")
    (:key ":capricorn:" :codepoint "\x2651" :description "capricorn")
    (:key ":aquarius:" :codepoint "\x2652" :description "aquarius")
    (:key ":pisces:" :codepoint "\x2653" :description "pisces")
    (:key ":ophiuchus:" :codepoint "\x26ce" :description "ophiuchus")
    (:key ":six_pointed_star:" :codepoint "\x1f52f" :description "six pointed star with middle dot")
    (:key ":atm:" :codepoint "\x1f3e7" :description "automated teller machine")
    (:key ":chart:" :codepoint "\x1f4b9" :description "chart with upwards trend and yen sign")
    (:key ":heavy_dollar_sign:" :codepoint "\x1f4b2" :description "heavy dollar sign")
    (:key ":currency_exchange:" :codepoint "\x1f4b1" :description "currency exchange")
    (:key ":copyright:" :codepoint "\xa9" :description "copyright sign")
    (:key ":registered:" :codepoint "\xae" :description "registered sign")
    (:key ":tm:" :codepoint "\x2122" :description "trade mark sign")
    (:key ":x:" :codepoint "\x274c" :description "cross mark")
    (:key ":bangbang:" :codepoint "\x203c" :description "double exclamation mark")
    (:key ":interrobang:" :codepoint "\x2049" :description "exclamation question mark")
    (:key ":exclamation:" :codepoint "\x2757" :description "heavy exclamation mark symbol")
    (:key ":question:" :codepoint "\x2753" :description "black question mark ornament")
    (:key ":grey_exclamation:" :codepoint "\x2755" :description "white exclamation mark ornament")
    (:key ":grey_question:" :codepoint "\x2754" :description "white question mark ornament")
    (:key ":o:" :codepoint "\x2b55" :description "heavy large circle")
    (:key ":top:" :codepoint "\x1f51d" :description "top with upwards arrow above")
    (:key ":end:" :codepoint "\x1f51a" :description "end with leftwards arrow above")
    (:key ":back:" :codepoint "\x1f519" :description "back with leftwards arrow above")
    (:key ":on:" :codepoint "\x1f51b" :description "on with exclamation mark with left right arrow above")
    (:key ":soon:" :codepoint "\x1f51c" :description "soon with rightwards arrow above")
    (:key ":arrows_clockwise:" :codepoint "\x1f503" :description "clockwise downwards and upwards open circle arrows")
    (:key ":clock12:" :codepoint "\x1f55b" :description "clock face twelve oclock")
    (:key ":clock1230:" :codepoint "\x1f567" :description "clock face twelve-thirty")
    (:key ":clock1:" :codepoint "\x1f550" :description "clock face one oclock")
    (:key ":clock130:" :codepoint "\x1f55c" :description "clock face one-thirty")
    (:key ":clock2:" :codepoint "\x1f551" :description "clock face two oclock")
    (:key ":clock230:" :codepoint "\x1f55d" :description "clock face two-thirty")
    (:key ":clock3:" :codepoint "\x1f552" :description "clock face three oclock")
    (:key ":clock330:" :codepoint "\x1f55e" :description "clock face three-thirty")
    (:key ":clock4:" :codepoint "\x1f553" :description "clock face four oclock")
    (:key ":clock430:" :codepoint "\x1f55f" :description "clock face four-thirty")
    (:key ":clock5:" :codepoint "\x1f554" :description "clock face five oclock")
    (:key ":clock530:" :codepoint "\x1f560" :description "clock face five-thirty")
    (:key ":clock6:" :codepoint "\x1f555" :description "clock face six oclock")
    (:key ":clock7:" :codepoint "\x1f556" :description "clock face seven oclock")
    (:key ":clock8:" :codepoint "\x1f557" :description "clock face eight oclock")
    (:key ":clock9:" :codepoint "\x1f558" :description "clock face nine oclock")
    (:key ":clock10:" :codepoint "\x1f559" :description "clock face ten oclock")
    (:key ":clock11:" :codepoint "\x1f55a" :description "clock face eleven oclock")
    (:key ":clock630:" :codepoint "\x1f561" :description "clock face six-thirty")
    (:key ":clock730:" :codepoint "\x1f562" :description "clock face seven-thirty")
    (:key ":clock830:" :codepoint "\x1f563" :description "clock face eight-thirty")
    (:key ":clock930:" :codepoint "\x1f564" :description "clock face nine-thirty")
    (:key ":clock1030:" :codepoint "\x1f565" :description "clock face ten-thirty")
    (:key ":clock1130:" :codepoint "\x1f566" :description "clock face eleven-thirty")
    (:key ":heavy_multiplication_x:" :codepoint "\x2716" :description "heavy multiplication x")
    (:key ":heavy_plus_sign:" :codepoint "\x2795" :description "heavy plus sign")
    (:key ":heavy_minus_sign:" :codepoint "\x2796" :description "heavy minus sign")
    (:key ":heavy_division_sign:" :codepoint "\x2797" :description "heavy division sign")
    (:key ":spades:" :codepoint "\x2660" :description "black spade suit")
    (:key ":hearts:" :codepoint "\x2665" :description "black heart suit")
    (:key ":clubs:" :codepoint "\x2663" :description "black club suit")
    (:key ":diamonds:" :codepoint "\x2666" :description "black diamond suit")
    (:key ":white_flower:" :codepoint "\x1f4ae" :description "white flower")
    (:key ":100:" :codepoint "\x1f4af" :description "hundred points symbol")
    (:key ":heavy_check_mark:" :codepoint "\x2714" :description "heavy check mark")
    (:key ":ballot_box_with_check:" :codepoint "\x2611" :description "ballot box with check")
    (:key ":radio_button:" :codepoint "\x1f518" :description "radio button")
    (:key ":link:" :codepoint "\x1f517" :description "link symbol")
    (:key ":curly_loop:" :codepoint "\x27b0" :description "curly loop")
    (:key ":wavy_dash:" :codepoint "\x3030" :description "wavy dash")
    (:key ":part_alternation_mark:" :codepoint "\x303d" :description "part alternation mark")
    (:key ":trident:" :codepoint "\x1f531" :description "trident emblem")
    (:key ":black_medium_square:" :codepoint "\x25fc" :description "black medium square")
    (:key ":white_medium_square:" :codepoint "\x25fb" :description "white medium square")
    (:key ":black_medium_small_square:" :codepoint "\x25fe" :description "black medium small square")
    (:key ":white_medium_small_square:" :codepoint "\x25fd" :description "white medium small square")
    (:key ":black_small_square:" :codepoint "\x25aa" :description "black small square")
    (:key ":white_small_square:" :codepoint "\x25ab" :description "white small square")
    (:key ":small_red_triangle:" :codepoint "\x1f53a" :description "up-pointing red triangle")
    (:key ":black_square_button:" :codepoint "\x1f532" :description "black square button")
    (:key ":white_square_button:" :codepoint "\x1f533" :description "white square button")
    (:key ":black_circle:" :codepoint "\x26ab" :description "medium black circle")
    (:key ":white_circle:" :codepoint "\x26aa" :description "medium white circle")
    (:key ":red_circle:" :codepoint "\x1f534" :description "large red circle")
    (:key ":large_blue_circle:" :codepoint "\x1f535" :description "large blue circle")
    (:key ":small_red_triangle_down:" :codepoint "\x1f53b" :description "down-pointing red triangle")
    (:key ":white_large_square:" :codepoint "\x2b1c" :description "white large square")
    (:key ":black_large_square:" :codepoint "\x2b1b" :description "black large square")
    (:key ":large_orange_diamond:" :codepoint "\x1f536" :description "large orange diamond")
    (:key ":large_blue_diamond:" :codepoint "\x1f537" :description "large blue diamond")
    (:key ":small_orange_diamond:" :codepoint "\x1f538" :description "small orange diamond")
    (:key ":small_blue_diamond:" :codepoint "\x1f539" :description "small blue diamond")
))
(provide 'ac-emoji-data)